/**
 * ARCH-002 Block 5: Kysely Generator
 *
 * Generates Kysely-idiomatic types from schema.
 *
 * Type idioms:
 * - Generated<T> for primaryKey or default columns (DB generates value)
 * - ColumnType<SelectType, InsertType, UpdateType> for timestamps
 * - Plain types for regular columns
 */

import type {
	ResolvedSchema,
	SchemaColumnDefinition,
	ColumnType as SchemaColumnType,
} from '@dbsp/core';

export interface KyselyOutput {
	/** Generated DB interface file content */
	dbInterface: string;
	/** Generated table types file content */
	tableTypes: string;
}

/**
 * Map schema column types to TypeScript types.
 */
const TYPE_MAP: Record<SchemaColumnType, string> = {
	uuid: 'string',
	string: 'string',
	text: 'string',
	number: 'number',
	integer: 'number',
	bigint: 'bigint',
	decimal: 'string', // Decimal as string to preserve precision
	boolean: 'boolean',
	timestamp: 'Date',
	datetime: 'Date',
	date: 'Date',
	time: 'string',
	json: 'unknown',
	jsonb: 'unknown',
};

/**
 * Generate Kysely types from schema.
 */
export function generateKysely(schema: ResolvedSchema): KyselyOutput {
	const dbInterface = generateDbInterface(schema);
	const tableTypes = generateTableTypes(schema);

	return { dbInterface, tableTypes };
}

/**
 * Generate the DB interface file.
 */
function generateDbInterface(schema: ResolvedSchema): string {
	const lines: string[] = [];

	// Header
	lines.push('/**');
	lines.push(' * Generated by dbsp generate kysely');
	lines.push(' * DO NOT EDIT - this file is auto-generated');
	lines.push(' */');
	lines.push('');

	// Import table types
	const tableNames = Object.keys(schema.tables);
	lines.push(`import type {`);
	for (const name of tableNames) {
		lines.push(`\t${pascalCase(name)}Table,`);
	}
	lines.push(`} from './types.js';`);
	lines.push('');

	// DB interface
	lines.push('export interface DB {');
	for (const name of tableNames) {
		lines.push(`\t${name}: ${pascalCase(name)}Table;`);
	}
	lines.push('}');
	lines.push('');

	return lines.join('\n');
}

/**
 * Generate the table types file.
 */
function generateTableTypes(schema: ResolvedSchema): string {
	const lines: string[] = [];
	const timestamps = new Set(schema.conventions.timestamps);

	// Header
	lines.push('/**');
	lines.push(' * Generated by dbsp generate kysely');
	lines.push(' * DO NOT EDIT - this file is auto-generated');
	lines.push(' */');
	lines.push('');

	// Import Kysely types
	lines.push("import type { Generated, ColumnType } from 'kysely';");
	lines.push('');

	// Generate each table type
	for (const [tableName, table] of Object.entries(schema.tables)) {
		lines.push(`export interface ${pascalCase(tableName)}Table {`);

		for (const [colName, colDef] of Object.entries(table)) {
			const tsType = generateColumnType(colName, colDef, timestamps);
			lines.push(`\t${colName}: ${tsType};`);
		}

		lines.push('}');
		lines.push('');
	}

	return lines.join('\n');
}

/**
 * Generate TypeScript type for a column.
 *
 * Rules:
 * - primaryKey or default → Generated<T>
 * - timestamps → ColumnType<Date, Date | string, Date | string>
 * - nullable → T | null
 * - otherwise → plain type
 */
function generateColumnType(
	colName: string,
	col: SchemaColumnDefinition,
	timestamps: Set<string>,
): string {
	const baseType = TYPE_MAP[col.type] ?? 'unknown';

	// Timestamps get ColumnType for flexible insert/update
	if (timestamps.has(colName)) {
		const selectType = 'Date';
		const insertType = col.default
			? 'Date | string | undefined'
			: 'Date | string';
		const updateType = 'Date | string';
		return `ColumnType<${selectType}, ${insertType}, ${updateType}>`;
	}

	// Primary key or default → Generated
	if (col.primaryKey || col.default) {
		if (col.nullable) {
			return `Generated<${baseType} | null>`;
		}
		return `Generated<${baseType}>`;
	}

	// Nullable
	if (col.nullable) {
		return `${baseType} | null`;
	}

	return baseType;
}

/**
 * Convert snake_case or camelCase to PascalCase.
 */
function pascalCase(str: string): string {
	return str
		.split(/[_-]/)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join('');
}
