/**
 * ARCH-002 Block 4: Manifest Generator
 *
 * Generates a TypeScript file containing the schema as plain JSON-serializable objects.
 * This is used at runtime by the ORM - no Map/Set/bigint, only plain objects.
 */

import type {
	ColumnDefinition,
	RelationDefinition,
	ResolvedSchema,
} from '@db-semantic-planner/schema';

export interface ManifestOutput {
	/** Generated TypeScript code */
	code: string;
}

/**
 * Generate manifest TypeScript file from schema.
 *
 * Output is a plain object (JSON-serializable) that can be imported at runtime.
 */
export function generateManifest(schema: ResolvedSchema): ManifestOutput {
	const lines: string[] = [];

	// Header
	lines.push('/**');
	lines.push(' * Generated by dbsp generate manifest');
	lines.push(' * DO NOT EDIT - this file is auto-generated');
	lines.push(' */');
	lines.push('');

	// Tables type
	lines.push('export const tables = {');
	for (const [tableName, table] of Object.entries(schema.tables)) {
		lines.push(`\t${safeKey(tableName)}: {`);
		for (const [colName, colDef] of Object.entries(table)) {
			lines.push(`\t\t${safeKey(colName)}: ${serializeColumn(colDef)},`);
		}
		lines.push('\t},');
	}
	lines.push('} as const;');
	lines.push('');

	// Relations
	lines.push('export const relations = {');
	for (const [key, rel] of Object.entries(schema.relations)) {
		lines.push(`\t${safeKey(key)}: ${serializeRelation(rel)},`);
	}
	lines.push('} as const;');
	lines.push('');

	// Hints
	lines.push('export const hints = {');
	for (const [key, hint] of Object.entries(schema.hints)) {
		const parts: string[] = [];
		if (hint.defaultStrategy)
			parts.push(`defaultStrategy: '${hint.defaultStrategy}'`);
		if (hint.cardinality) parts.push(`cardinality: '${hint.cardinality}'`);
		lines.push(`\t${safeKey(key)}: { ${parts.join(', ')} },`);
	}
	lines.push('} as const;');
	lines.push('');

	// Conventions
	lines.push('export const conventions = {');
	lines.push(`\tfkPattern: '${schema.conventions.fkPattern}',`);
	lines.push(`\tpluralize: ${schema.conventions.pluralize},`);
	lines.push(`\ttimestamps: ${JSON.stringify(schema.conventions.timestamps)},`);
	lines.push('} as const;');
	lines.push('');

	// Combined schema object
	lines.push('export const schema = {');
	lines.push('\ttables,');
	lines.push('\trelations,');
	lines.push('\thints,');
	lines.push('\tconventions,');
	lines.push('} as const;');
	lines.push('');

	// Type export for convenience
	lines.push('export type Schema = typeof schema;');
	lines.push('');

	return { code: lines.join('\n') };
}

/**
 * Make a key safe for object literal syntax.
 */
function safeKey(key: string): string {
	// If key contains dots or special chars, quote it
	if (/[^a-zA-Z0-9_$]/.test(key)) {
		return `'${key}'`;
	}
	return key;
}

/**
 * Serialize a column definition to TypeScript object literal.
 */
function serializeColumn(col: ColumnDefinition): string {
	const parts: string[] = [];
	parts.push(`type: '${col.type}'`);

	if (col.primaryKey) parts.push('primaryKey: true');
	if (col.nullable !== undefined) parts.push(`nullable: ${col.nullable}`);
	if (col.unique) parts.push('unique: true');
	if (col.default) parts.push(`default: '${col.default}'`);

	if (col.references) {
		const refParts = [`table: '${col.references.table}'`];
		if (col.references.column) {
			refParts.push(`column: '${col.references.column}'`);
		}
		parts.push(`references: { ${refParts.join(', ')} }`);
	}

	return `{ ${parts.join(', ')} }`;
}

/**
 * Serialize a relation definition to TypeScript object literal.
 */
function serializeRelation(rel: RelationDefinition): string {
	const parts: string[] = [];
	parts.push(`kind: '${rel.kind}'`);
	parts.push(`target: '${rel.target}'`);

	switch (rel.kind) {
		case 'belongsTo':
			parts.push(`foreignKey: '${rel.foreignKey}'`);
			if (rel.targetKey) parts.push(`targetKey: '${rel.targetKey}'`);
			break;
		case 'hasMany':
			parts.push(`foreignKey: '${rel.foreignKey}'`);
			if (rel.sourceKey) parts.push(`sourceKey: '${rel.sourceKey}'`);
			break;
		case 'manyToMany':
			parts.push(`through: '${rel.through}'`);
			parts.push(`sourceFk: '${rel.sourceFk}'`);
			parts.push(`targetFk: '${rel.targetFk}'`);
			break;
	}

	return `{ ${parts.join(', ')} }`;
}
