/**
 * CLI-DDL: Schema Codegen Module
 *
 * Generates TypeScript schema files from IntrospectedModelIR.
 * Used by `dbsp introspect` to create dbsp.schema.ts from a database.
 */

import type { ModelIR, TableIR } from '@dbsp/core';

/**
 * Options for schema code generation.
 */
export interface SchemaCodegenOptions {
	/** Source database URL (for comment header) */
	readonly sourceUrl?: string;
	/** Include original DB types as comments */
	readonly includeDbTypeComments?: boolean;
	/** Warnings from introspection to include as comments */
	readonly warnings?: readonly string[];
	/** Timestamp of introspection */
	readonly introspectedAt?: Date;
}

/**
 * Generate column definition object code.
 */
function generateColumnCode(
	column: TableIR['columns'][number],
	isPrimaryKey: boolean,
	foreignKeyRef: { table: string; column?: string } | undefined,
	options: SchemaCodegenOptions,
): string {
	const props: string[] = [];

	// Type is always required (ColumnType values are the same in core and schema)
	props.push(`type: '${column.type}'`);

	// Primary key
	if (isPrimaryKey) {
		props.push('primaryKey: true');
	}

	// Nullable (only add if true, false is default)
	if (column.nullable) {
		props.push('nullable: true');
	}

	// Default value
	if (column.default !== undefined) {
		const defaultStr =
			typeof column.default === 'string'
				? `'${column.default}'`
				: String(column.default);
		props.push(`default: ${defaultStr}`);
	}

	// Foreign key reference
	if (foreignKeyRef) {
		if (foreignKeyRef.column && foreignKeyRef.column !== 'id') {
			props.push(
				`references: { table: '${foreignKeyRef.table}', column: '${foreignKeyRef.column}' }`,
			);
		} else {
			props.push(`references: { table: '${foreignKeyRef.table}' }`);
		}
	}

	// Build the object
	let code = `{ ${props.join(', ')} }`;

	// Add comment for original DB type if requested
	if (options.includeDbTypeComments && column.originalDbType) {
		code += ` /* from: ${column.originalDbType} */`;
	}

	return code;
}

/**
 * Generate table definition code.
 */
function generateTableCode(
	table: TableIR,
	options: SchemaCodegenOptions,
): string {
	// Build FK lookup map: column name -> { table, column }
	const fkMap = new Map<string, { table: string; column?: string }>();
	for (const fk of table.foreignKeys) {
		const localCol = fk.columns[0];
		const refCol = fk.references.columns[0];
		if (
			fk.columns.length === 1 &&
			fk.references.columns.length === 1 &&
			localCol &&
			refCol
		) {
			// exactOptionalPropertyTypes: omit 'column' when it's 'id' (the default)
			const entry: { table: string; column?: string } = {
				table: fk.references.table,
			};
			if (refCol !== 'id') {
				entry.column = refCol;
			}
			fkMap.set(localCol, entry);
		}
	}

	const columnLines = table.columns.map((col) => {
		const isPrimaryKey =
			typeof table.primaryKey === 'string'
				? col.name === table.primaryKey
				: table.primaryKey.includes(col.name);
		const fkRef = fkMap.get(col.name);
		const code = generateColumnCode(col, isPrimaryKey, fkRef, options);
		return `\t\t${col.name}: ${code}`;
	});

	return `\t${table.name}: {\n${columnLines.join(',\n')},\n\t}`;
}

/**
 * Generate a TypeScript schema file from ModelIR.
 *
 * @param model - The ModelIR (or IntrospectedModelIR) to generate from
 * @param options - Code generation options
 * @returns TypeScript source code for a schema file
 */
export function generateSchemaFile(
	model: ModelIR,
	options: SchemaCodegenOptions = {},
): string {
	const lines: string[] = [];

	// Header comment
	lines.push('/**');
	lines.push(' * Auto-generated by: dbsp introspect');
	if (options.sourceUrl) {
		// Redact password in URL
		const redactedUrl = options.sourceUrl.replace(/:[^:@]+@/, ':***@');
		lines.push(` * Source: ${redactedUrl}`);
	}
	if (options.introspectedAt) {
		lines.push(` * Generated: ${options.introspectedAt.toISOString()}`);
	}
	lines.push(' *');
	if (options.warnings && options.warnings.length > 0) {
		lines.push(' * ⚠️ Warnings:');
		for (const warning of options.warnings) {
			lines.push(` *   - ${warning}`);
		}
	}
	lines.push(' * Review before using in production.');
	lines.push(' */');
	lines.push('');

	// Imports
	lines.push("import { defineSchema } from '@dbsp/core';");
	lines.push('');

	// Schema definition
	lines.push('export const schema = defineSchema({');

	// Generate each table
	const tables = Array.from(model.tables.values());
	const tableLines = tables.map((table) => generateTableCode(table, options));
	lines.push(tableLines.join(',\n\n'));

	lines.push('});');
	lines.push('');

	return lines.join('\n');
}
