/**
 * @dbsp/adapter-pgsql
 *
 * Native PostgreSQL adapter using tree-to-tree transformation:
 * PlanReport → PostgreSQL AST → SQL (via pgsql-deparser)
 */

// Assert & Convention helpers — public API
export {
	DEFAULT_PK_COLUMN,
	defaultFkDerivation,
	type FkColumnDerivation,
} from './assert-field.js';
// AST Helpers — public API (internal helpers remain in ./ast-helpers.js)
export { normalizeSQL } from './ast-helpers.js';
// Compiler
export {
	type BatchValuesJoinDecision,
	type CompiledResult,
	type CompilerOptions,
	compilePlan,
	isBatchValuesJoinDecision,
	isJoinDecision,
	isPrecompiledJoinDecision,
	type JoinDecision,
	PlanCompiler,
	type PlanDecision,
	type PrecompiledJoinDecision,
	type SimplifiedPlanReport,
} from './compiler.js';
// DDL Generation
export {
	type AddedEnumValue,
	assertCreateIndexesSupported,
	assertCreateIndexSupported,
	assertNoRepeatedExpressionSurfaceDrift,
	type ChangeKind,
	CheckConstraintNewEnumValueError,
	type ComparePgsqlDatabaseSchemaOptions,
	type CompareSchemataOptions,
	canGenerateCreateIndex,
	comparePgsqlDatabaseSchema,
	compareSchemata,
	type DiffSummary,
	ExpressionCanonicalizationUnavailableError,
	ExpressionKeyedIndexPredicateCanonicalizationUnsupportedError,
	ensureMigrationsTable,
	type GenerateDDLOptions,
	generateCreateIndex,
	generateDDL,
	generateDownSQL,
	generateMigrationFile,
	generateMigrationSQL,
	getAppliedMigrations,
	getNextSchemaVersion,
	type IndexCapabilityContext,
	IndexFeatureUnsupportedError,
	IndexPredicateCanonicalizationError,
	type IndexRenderSpec,
	isDestructiveDown,
	isMigrationApplied,
	type MigrationRecord,
	type MigrationSQLOptions,
	mapColumnType,
	mapOnDeleteAction,
	NonConvergentSchemaDiffError,
	type NonConvergentSchemaDiffSurface,
	type ParsedMigrationFile,
	PartialIndexPredicateNewEnumValueError,
	parseMigrationFile,
	RawIndexPredicateFallbackError,
	recordMigration,
	removeMigrationRecord,
	renderCreateIndex,
	type SchemaChange,
	type SchemaDiff,
	withMigrationLock,
} from './ddl/index.js';
// EXPLAIN support
export {
	buildExplain,
	buildExplainAnalyzeJson,
	buildExplainPlan,
	buildExplainVerbose,
	type ExplainFormat,
	type ExplainOptions,
	type ExplainPlan,
	getRowEstimates,
	getTotalExecutionTime,
	parseExplainJson,
} from './explain/index.js';
export {
	type CanonicalizeCheckConstraintsOptions,
	CheckConstraintCanonicalizationError,
	type CheckConstraintCanonicalizationWarning,
	ColumnDefaultCanonicalizationError,
	type ColumnDefaultCanonicalizationWarning,
	canonicalizeCheckConstraints,
	type ExpressionCanonicalizationWarning,
} from './expression-canonicalizer.js';
// Extensions (pgvector, ParadeDB, PG builtins)
export {
	bm25Search,
	booleanSearch,
	boost,
	cosineDistance,
	generateSeries,
	innerProduct,
	l2Distance,
	nextval,
	parse,
	rawDistance,
	score,
	vectorDims,
} from './extensions/index.js';
// Handler Registry — types only (implementation details remain in ./handlers/index.js)
export type {
	CompilerContext,
	CompilerState,
	Decision,
	ExpressionHandler,
	IncludeHandler,
	IncludeResult,
	WhereDispatcher,
	WhereHandler,
} from './handlers/index.js';
// Introspection
export {
	type DetectedHierarchy,
	type IntrospectedModelIR,
	type IntrospectionOptions,
	introspect,
	type SchemaScopeOptions,
} from './introspection.js';
// Mutations
export {
	buildOnConflictClause,
	type ConflictAction,
	type ConflictTarget,
	compileDelete,
	compileInsert,
	compileMutation,
	compileUpdate,
	compileUpsert,
	conditionalUpdate,
	type DeleteConfig,
	excludedRef,
	type InsertConfig,
	type UpdateConfig,
	type UpsertConfig,
} from './mutations/index.js';
// Naming resolution
export { resolveLogicalName } from './naming.js';
// Naming plugins
export {
	CamelCaseNamingPlugin,
	camelCaseNaming,
	getNamingPluginForDbCasing,
	IdentityNamingPlugin,
	identityNaming,
	type NamingPlugin,
} from './naming-plugin.js';
// ParamRef validation
export {
	collectAndValidateParamRefs,
	createAnyExpr,
	createEqualityExpr,
	createParamRef,
	createTypeCastParamRef,
	type ParamRefValidationResult,
	validateParamRef,
} from './param-ref.js';
// Adapter
export {
	createPgsqlAdapter,
	createPgsqlCompileOnlyAdapter,
	type PgAdvisoryLockKey,
	type PgAdvisoryLockResult,
	PgsqlAdapter,
	type PgsqlAdapterOptions,
	PgsqlAdvisoryLockOptionsError,
	type PgsqlBorrowedClientAdapterOptions,
	PgsqlPinnedConnectionAbortSignalError,
	type PgsqlPoolAdapterOptions,
	PgsqlRawSqlTransactionControlError,
	PgsqlTransactionAbortedCommitError,
	PgsqlTransactionAbortedError,
	PgsqlTransactionAbortSignalError,
	PgsqlTransactionOptionsError,
	PgsqlTransactionTimeoutError,
	type RollbackOnlyPgsqlScope,
} from './pgsql-adapter.js';
export { derivePostgresqlCapabilitiesForVersion } from './postgresql-capabilities.js';
// Redaction (params logging safety)
export {
	DEFAULT_REDACTION_PATTERNS,
	type RedactionConfig,
	type RedactionPattern,
	redactParams,
} from './redact-params.js';
// Set operations (UNION/INTERSECT/EXCEPT)
export {
	compileSetOperation,
	createLeafCompileFn,
	type LeafCompileFn,
	type SetOperationResult,
} from './set-operation.js';
// Streaming (cursor-based)
export {
	buildCloseCursor,
	buildDeclareCursor,
	buildFetch,
	buildFetchAll,
	buildFetchFirst,
	buildFetchForward,
	buildFetchNext,
	buildStreamingStatements,
	type CursorHoldOption,
	type CursorOptions,
	type CursorScrollOption,
	type FetchDirection,
	type FetchOptions,
	generateCursorName,
	type StreamConfig,
} from './streaming/index.js';
// ADR-0003 transition planner pack
export {
	ADD_CHECK_RULE_ID,
	ALTER_AUTHORITY_OBSERVATION,
	ALTER_COLUMN_SET_NOT_NULL_OPERATION_KIND,
	ALTER_TYPE_ADD_VALUE_OPERATION_KIND,
	type AlterColumnSetNotNullPayload,
	type AlterTypeAddValuePayload,
	ATTACH_LOGICAL_IDENTITY_OPERATION_KIND,
	type AttachLogicalIdentityPayload,
	acquirePgLedgerLocks,
	acquirePgTransitionClient,
	appendPgLedgerClaim,
	appendPgLedgerProgress,
	appendPgLedgerResolution,
	appendTransitionAuthorization,
	COLUMN_EXISTS_OBSERVATION,
	createAlterColumnSetNotNullOperationRuntime,
	createAlterTypeAddValueOperationRuntime,
	createAttachLogicalIdentityOperationRuntime,
	createEnumAddValueRule,
	createLogicalIdentityAdoptionRule,
	createManualSqlOperationRuntime,
	createPgExecutionContract,
	createPgObservationIssuer,
	createPgTransitionLessor,
	createPgTransitionPack,
	createPgTransitionRunPersister,
	createSetNotNullRule,
	DBSP_LEDGER_EVENT_TABLE,
	DBSP_LEDGER_IDENTITY_TABLE,
	DBSP_LEDGER_MARKER_TABLE,
	DBSP_LEDGER_RESERVATION_TABLE,
	DBSP_LOGICAL_IDENTITY_TABLE,
	DBSP_META_SCHEMA,
	DBSP_TRANSITION_AUTHORIZATION_TABLE,
	DBSP_TRANSITION_JOURNAL_TABLE,
	DBSP_TRANSITION_RUN_PLAN_TABLE,
	DBSP_TRANSITION_RUN_TABLE,
	ENGINE_VERSION_OBSERVATION,
	ENUM_ADD_VALUE_RULE_ID,
	ENUM_LABEL_VISIBLE_OBSERVATION,
	ENUM_TYPE_EXISTS_OBSERVATION,
	type EnumAddValueMatch,
	type EnumAddValueRuleOptions,
	ensureDbspMetaLedger,
	ensurePgLedger,
	ensurePgLedgerStorageVersion,
	ensureTransitionJournal,
	evaluatePgExecutionContract,
	executePgManagedBundle,
	executePgObservationFromLessor,
	findPgLedgerTerminalMember,
	type IdentityAdoptionAsserter,
	LOGICAL_IDENTITY_ADOPTION_RULE_ID,
	LOGICAL_IDENTITY_CARRIER_OBSERVATION,
	type LogicalIdentityAdoptionMatch,
	type LogicalIdentityAdoptionRuleOptions,
	MANUAL_SQL_OPERATION_KIND,
	type ManualSqlPayload,
	NO_NULLS_GUARD,
	normalizeManualSqlPayload,
	openPgOutcomeClaim,
	PG_INTROSPECTION_ARTIFACT,
	PG_LEDGER_SHAPE_VERSION,
	PG_OPERATION_PACK_ARTIFACT,
	PG_RULE_PACK_ARTIFACT,
	type PgCatalogueIdentityQueryable,
	PgExecutionContractDerivationError,
	type PgLedgerAddressChain,
	type PgLedgerLockResult,
	PgLedgerStorageUnsupportedError,
	type PgLedgerTarget,
	type PgOutcomeClaimRequest,
	type PgOutcomeExecutionRequest,
	type PgOutcomeNonTransactionalRequest,
	type PgOutcomeResolution,
	type PgOutcomeResult,
	type PgOutcomeTransactionalRequest,
	type PgReinitializePreflightOptions,
	type PgReinitializePreflightPool,
	type PgTransitionClientLease,
	type PgTransitionPackOptions,
	pgTargetIdentityMismatch,
	preparePgExecutionSession,
	preparePgRecoveryAdmission,
	readPgCatalogueIdentity,
	readPgExecutionTargetFromClient,
	readPgLedgerAddressChain,
	readPgObservationContextFromLessor,
	readTransitionJournal,
	recordPgLedgerIdentity,
	renderAlterColumnSetNotNullSql,
	renderAlterTypeAddValueSql,
	renderAttachLogicalIdentityLockSql,
	renderCreateDbspMetaSchemaSql,
	renderCreateLedgerEventTableSql,
	renderCreateLedgerIdentityTableSql,
	renderCreateLedgerImmutabilityFunctionSql,
	renderCreateLedgerImmutabilityTriggerSql,
	renderCreateLedgerMarkerTableSql,
	renderCreateLedgerReservationTableSql,
	renderCreateLedgerTerminalMemberIndexSql,
	renderCreateLogicalIdentityIndexesSql,
	renderCreateLogicalIdentitySideTableSql,
	renderCreateTransitionAuthorizationTableSql,
	renderCreateTransitionJournalTableSql,
	renderCreateTransitionRunPlanTableSql,
	renderCreateTransitionRunTableSql,
	renderInsertLogicalIdentitySql,
	renderNoNullsCheckSql,
	renderSetNotNullLockSql,
	runPgNonTransactionalOutcome,
	runPgReinitializePreflight,
	runPgTransactionalOutcome,
	SET_NOT_NULL_RULE_ID,
	type SetNotNullMatch,
	type SetNotNullRuleOptions,
	withPgTransitionRunLock,
} from './transition/index.js';
// Validation
export {
	escapeDiagnosticText,
	InvalidIdentifierError,
	isReservedKeyword,
	sanitizeForDisplay,
	validateIdentifier,
	validateIdentifiers,
	validateQualifiedIdentifier,
	validateSqlExpression,
} from './validate.js';
