packages:
  - "packages/*"
allowBuilds:
  b: true
  d: true
  e: true
  i: true
  l: true
  s: true
  u: true

catalog:
  # UI / CLI

  # Build / Dev tools
  '@biomejs/biome': ^2.4.13
  '@inkjs/ui': ^2.0.0

  # Other
  '@modelcontextprotocol/sdk': ^1.29.0

  # Testing
  '@testcontainers/postgresql': ^11.14.0
  '@types/better-sqlite3': ^7.6.13
  '@types/node': ^25.6.0
  '@types/pg': ^8.20.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  better-sqlite3: ^12.6.0

  # Parser
  chevrotain: ^12.0.0
  commander: ^14.0.3
  hono: ^4.12.14
  ink: ^7.0.1
  ink-table: ^3.1.0

  # Database
  pg: ^8.20.0
  react: ^19.2.5
  react-dom: ^19.2.5
  tsup: ^8.5.1
  tsx: ^4.21.0

  # Documentation
  typedoc: ^0.28.19
  typescript: ~5.9.3

  # Schema / Validation
  valibot: ^1.3.1
  vitest: ^4.1.5
