/**
 * SQL predicate for PostgreSQL defaults generated by SERIAL/BIGSERIAL.
 *
 * The aliases are supplied by the caller because this predicate is shared by
 * catalog queries with different surrounding SELECT lists.
 */
export function generatedSequenceDefaultPredicate(aliases: {
	readonly relation: string;
	readonly attribute: string;
	readonly attrdef: string;
}): string {
	const { relation, attribute, attrdef } = aliases;
	return `(pg_catalog.pg_get_expr(${attrdef}.adbin, ${attrdef}.adrelid, false) ~ $dbsp_serial$^nextval\\('([^']|'')*'::regclass\\)$dbsp_serial$ AND EXISTS (SELECT 1 FROM pg_catalog.pg_depend default_sequence JOIN pg_catalog.pg_class sequence_relation ON sequence_relation.oid = default_sequence.refobjid WHERE default_sequence.classid = 'pg_catalog.pg_attrdef'::pg_catalog.regclass AND default_sequence.objid = ${attrdef}.oid AND default_sequence.refclassid = 'pg_catalog.pg_class'::pg_catalog.regclass AND default_sequence.deptype = 'n' AND sequence_relation.relkind = 'S' AND EXISTS (SELECT 1 FROM pg_catalog.pg_depend ownership WHERE ownership.classid = 'pg_catalog.pg_class'::pg_catalog.regclass AND ownership.objid = sequence_relation.oid AND ownership.refclassid = 'pg_catalog.pg_class'::pg_catalog.regclass AND ownership.refobjid = ${relation}.oid AND ownership.refobjsubid = ${attribute}.attnum AND ownership.deptype = 'a')))`;
}
