import { createHash } from 'node:crypto';
import type {
	DeclarableResourceAddress,
	LedgerClaimKind,
	NormalizedManagedStep,
} from '@dbsp/types';
import { canonicalResourceParent } from '@dbsp/types';
import { splitCheckConstraintState } from '../check-expression.js';
import { renderColumnDbType } from '../db-type.js';
import { decideColumnEmission } from './column-emission-decision.js';
import {
	classifyGeneratedMutation,
	type GeneratedMutationClassification,
} from './destructive-classification.js';
import { formatSqlDefault } from './phases/utils.js';
import type { ChangeKind, SchemaChange } from './schema-diff.js';

type Address = DeclarableResourceAddress & {
	readonly scope: 'schema' | 'database';
};

type Meta = Readonly<Record<string, unknown>>;

export type GeneratedColumnPostcondition = {
	readonly name: string;
	readonly type?: string;
	readonly nullable?: boolean;
	readonly hasDefault?: boolean;
	/** Whether a required default was authored or generated by SERIAL/BIGSERIAL. */
	readonly defaultKind?: 'authored' | 'generated-sequence';
	readonly default?: string;
	readonly collation?: string | null;
	readonly identity?: 'always' | 'byDefault' | null;
};

export type GeneratedConstraintPostcondition =
	| {
			readonly type: 'p' | 'u';
			readonly columns: readonly string[];
			readonly deferrable: boolean;
			readonly initiallyDeferred: boolean;
			readonly enforced: boolean;
	  }
	| {
			readonly type: 'f';
			readonly columns: readonly string[];
			readonly references: {
				readonly schema: string;
				readonly table: string;
				readonly columns: readonly string[];
			};
			readonly onDelete: GeneratedForeignKeyAction;
			readonly onUpdate: GeneratedForeignKeyAction;
			readonly deferrable: boolean;
			readonly initiallyDeferred: boolean;
			readonly enforced: boolean;
			readonly notValid: boolean;
	  }
	| {
			readonly type: 'c';
			/** The ModelIR CHECK expression, never a rendered constraint definition. */
			readonly expression: string;
			readonly notValid: boolean;
	  };

/** The semantic FK actions PostgreSQL can represent in pg_constraint. */
export type GeneratedForeignKeyAction =
	| 'NO ACTION'
	| 'RESTRICT'
	| 'CASCADE'
	| 'SET NULL'
	| 'SET DEFAULT';

export type GeneratedIndexPostcondition = {
	/** The identity is persisted separately from the rendered CREATE INDEX SQL. */
	readonly schema: string;
	readonly table: string;
	readonly name: string;
	/** PostgreSQL exposes an omitted method as btree; make that expectation explicit. */
	readonly method: string;
	readonly unique: boolean;
	readonly valid: true;
	readonly ready: true;
	readonly live: true;
	readonly columns: readonly string[];
	readonly expressions?: readonly string[];
	readonly include?: readonly string[];
	readonly nullsNotDistinct: boolean;
	readonly opclass?: Readonly<Record<string, string>>;
	readonly with?: Readonly<Record<string, string>>;
	readonly where?: string;
};

/** A canonical SQL fact, never an unversioned deparse string. */
export type CanonicalSqlFact = {
	readonly canonicalFormVersion: 1;
	readonly sql: string;
};

/**
 * The default, identity, and expression facts are one discriminated state.
 * In particular, an identity cannot also claim an authored/default sequence
 * expression, and a missing default cannot carry an expression.
 */
export type GeneratedColumnDefaultState =
	| {
			readonly defaultKind: 'none';
			readonly hasDefault: false;
			readonly identity: null;
			readonly defaultExpression?: never;
	  }
	| {
			readonly defaultKind: 'authored';
			readonly hasDefault: true;
			readonly identity: null;
			readonly defaultExpression: CanonicalSqlFact;
	  }
	| {
			readonly defaultKind: 'generated-sequence';
			readonly hasDefault: true;
			readonly identity: null;
			readonly defaultExpression?: never;
	  }
	| {
			readonly defaultKind: 'identity';
			readonly hasDefault: false;
			readonly identity: 'always' | 'byDefault';
			readonly defaultExpression?: never;
	  };

type GeneratedColumnDeclaration = {
	readonly type?: string;
	readonly nullable?: boolean;
	/** null means no COLLATE clause was authored; it is not an effective default. */
	readonly authoredCollation?: string | null;
	readonly default?: GeneratedColumnDefaultState;
};

type GeneratedTableColumnDeclaration = GeneratedColumnDeclaration & {
	/** A table-shape member name, not the table target binding. */
	readonly name: string;
};

type GeneratedIndexDeclaration = Omit<
	GeneratedIndexPostcondition,
	'schema' | 'table' | 'name' | 'expressions' | 'where'
> & {
	readonly expressions?: readonly CanonicalSqlFact[];
	readonly where?: CanonicalSqlFact;
};

type GeneratedConstraintDeclaration =
	| Extract<GeneratedConstraintPostcondition, { readonly type: 'p' | 'u' }>
	| Extract<GeneratedConstraintPostcondition, { readonly type: 'f' }>;

/** Table names live only in TargetBinding; columns describe table structure. */
type V3TableDeclaration = {
	readonly kind: 'table';
	readonly columns: readonly GeneratedTableColumnDeclaration[];
};
/** Column names live only in TargetBinding; this is the column's shape. */
type V3ColumnDeclaration = {
	readonly kind: 'column';
	readonly column: GeneratedColumnDeclaration;
};
/** Constraint names live only in TargetBinding; this is a non-CHECK constraint fact. */
type V3ConstraintDeclaration = {
	readonly kind: 'constraint';
	readonly constraint: GeneratedConstraintDeclaration;
};
/** CHECK names live only in TargetBinding; expression is canonical and versioned. */
type V3CheckDeclaration = {
	readonly kind: 'check';
	readonly check: {
		readonly expression: CanonicalSqlFact;
		readonly notValid: boolean;
	};
};
/** Index schema, table, and name live only in TargetBinding; options are structured facts. */
type V3IndexDeclaration = {
	readonly kind: 'index';
	readonly index: GeneratedIndexDeclaration;
};
/** Enum names live only in TargetBinding; labels are the declaration. */
type V3EnumDeclaration = {
	readonly kind: 'enum';
	readonly labels: readonly string[];
};
/** Sequence names live only in TargetBinding; options are the declaration. */
type V3SequenceDeclaration = {
	readonly kind: 'sequence';
	readonly startValue?: string;
	readonly incrementBy?: string;
	readonly minValue?: string;
	readonly maxValue?: string;
	readonly cycle?: boolean;
};
/** Extension names live only in TargetBinding; requested version is the declaration. */
type V3ExtensionDeclaration = {
	readonly kind: 'extension';
	readonly version?: string;
};

/** Address-free v3 declaration variants. */
export type GeneratedPostconditionDeclarationV3 = {
	readonly canonicalFormVersion: 1;
} & (
	| V3TableDeclaration
	| V3ColumnDeclaration
	| V3ConstraintDeclaration
	| V3CheckDeclaration
	| V3IndexDeclaration
	| V3EnumDeclaration
	| V3SequenceDeclaration
	| V3ExtensionDeclaration
	| { readonly kind: 'absent' }
);

/**
 * The separate binding selects the surrounding managed step's canonical
 * address.  It is versioned independently so later verifiers can resolve it
 * without teaching any declaration variant about physical addresses.
 */
export type TargetBinding = {
	readonly bindingVersion: 1;
	readonly bindingKind: 'managed-step-address';
};

/** Version 3 carries an address-free declaration and a separately decoded binding. */
export type GeneratedPostconditionV3 = {
	readonly postconditionVersion: 3;
	/** v3 kind lives only in the address-free declaration, never beside the binding. */
	readonly kind?: never;
	readonly declaration: GeneratedPostconditionDeclarationV3;
	readonly targetBinding: TargetBinding;
};

/** Only v3 is a decodable generated postcondition. Older values replan. */
export type GeneratedPostcondition = GeneratedPostconditionV3;

/**
 * JSON-compatible serialization whose object-member order survives PostgreSQL
 * jsonb normalization. Arrays intentionally retain their supplied order.
 */
function canonicalGeneratedPostconditionJson(value: unknown): string {
	if (value === null) return 'null';
	if (value === undefined)
		throw new TypeError(
			'generated postcondition digest cannot serialize undefined values',
		);
	if (Array.isArray(value)) {
		const entries: string[] = [];
		for (let index = 0; index < value.length; index += 1) {
			if (!Object.hasOwn(value, index))
				throw new TypeError(
					'generated postcondition digest cannot serialize undefined array members',
				);
			entries.push(canonicalGeneratedPostconditionJson(value[index]));
		}
		return `[${entries.join(',')}]`;
	}
	if (typeof value === 'object') {
		const record = value as Record<string, unknown>;
		return `{${Object.keys(record)
			.sort((left, right) => (left < right ? -1 : left > right ? 1 : 0))
			.map((key) => {
				const member = record[key];
				if (member === undefined)
					throw new TypeError(
						'generated postcondition digest cannot serialize undefined object members',
					);
				return `${JSON.stringify(key)}:${canonicalGeneratedPostconditionJson(member)}`;
			})
			.join(',')}}`;
	}
	if (typeof value === 'number' && !Number.isFinite(value))
		throw new TypeError(
			'generated postcondition digest can only serialize finite numbers',
		);
	if (
		typeof value !== 'string' &&
		typeof value !== 'boolean' &&
		typeof value !== 'number'
	)
		throw new TypeError(
			'generated postcondition digest can only serialize JSON values',
		);
	return JSON.stringify(value);
}

/** The version tag is part of the digest domain, never an implicit convention. */
export function generatedPostconditionDigest(value: {
	readonly postconditionVersion: number;
}): string {
	return createHash('sha256')
		.update(`generated-postcondition:v${value.postconditionVersion}\u0000`)
		.update(canonicalGeneratedPostconditionJson(value))
		.digest('hex');
}

function postconditionPayload(
	value: GeneratedPostcondition,
): import('@dbsp/types').LedgerPayload {
	return {
		value: value as unknown as import('@dbsp/types').JsonValue,
		digest: generatedPostconditionDigest(value),
	};
}

function canonicalSqlFact(sql: string): CanonicalSqlFact {
	return { canonicalFormVersion: 1, sql };
}

function targetBinding(): TargetBinding {
	return { bindingVersion: 1, bindingKind: 'managed-step-address' };
}

function requiredColumn(
	value: unknown,
	label: string,
): import('@dbsp/types').ColumnIR {
	if (!value || typeof value !== 'object' || Array.isArray(value))
		throw new Error(
			`generator planning refuses ${label}: missing typed column`,
		);
	const column = value as import('@dbsp/types').ColumnIR;
	if (typeof column.name !== 'string' || typeof column.nullable !== 'boolean')
		throw new Error(
			`generator planning refuses ${label}: missing typed column`,
		);
	return column;
}

function columnDefaultState(
	column: import('@dbsp/types').ColumnIR,
	schema: string,
): GeneratedColumnDefaultState {
	const { defaultKind } = decideColumnEmission(column, schema);
	const identity = column.identity ?? null;
	if (identity !== null) {
		if (defaultKind !== undefined)
			throw new Error(
				`generator planning refuses ${column.name}: identity and default are contradictory`,
			);
		return { defaultKind: 'identity', hasDefault: false, identity };
	}
	if (defaultKind === undefined)
		return { defaultKind: 'none', hasDefault: false, identity: null };
	if (defaultKind === 'generated-sequence')
		return {
			defaultKind: 'generated-sequence',
			hasDefault: true,
			identity: null,
		};
	return {
		defaultKind: 'authored',
		hasDefault: true,
		identity: null,
		defaultExpression: canonicalSqlFact(
			formatSqlDefault(column.default, 'generator postcondition'),
		),
	};
}

function columnDeclaration(
	column: import('@dbsp/types').ColumnIR,
	schema: string,
	primaryKey = false,
): GeneratedColumnDeclaration {
	return {
		type: renderColumnDbType(column, schema),
		nullable: primaryKey ? false : column.nullable,
		authoredCollation: column.collation ?? null,
		default: columnDefaultState(column, schema),
	};
}

function v3Payload(
	declaration: GeneratedPostconditionDeclarationV3,
): import('@dbsp/types').LedgerPayload {
	return postconditionPayload({
		postconditionVersion: 3,
		declaration,
		targetBinding: targetBinding(),
	});
}

function requiredRecord(
	value: unknown,
	label: string,
): Readonly<Record<string, unknown>> {
	if (!value || typeof value !== 'object' || Array.isArray(value))
		throw new Error(
			`generator planning refuses ${label}: missing typed declaration`,
		);
	return value as Readonly<Record<string, unknown>>;
}

function requiredList(value: unknown, label: string): readonly string[] {
	if (!Array.isArray(value) || value.some((item) => typeof item !== 'string'))
		throw new Error(
			`generator planning refuses ${label}: missing typed columns`,
		);
	return value as readonly string[];
}

function requiredColumnList(value: unknown, label: string): readonly string[] {
	if (
		!Array.isArray(value) ||
		value.length === 0 ||
		value.some((item) => typeof item !== 'string' || item.trim().length === 0)
	)
		throw new Error(
			`generator planning refuses ${label}: missing typed columns`,
		);
	return value as readonly string[];
}

type ValidateConstraintTarget =
	| {
			readonly kind: 'check';
			readonly check: Readonly<Record<string, unknown>>;
	  }
	| {
			readonly kind: 'foreign-key';
			readonly fk: Readonly<Record<string, unknown>>;
			readonly references: Readonly<Record<string, unknown>>;
	  };

/**
 * `validate_constraint` has exactly one branch discriminator. A defined
 * `check` is always a check declaration (and must therefore be a record);
 * only an absent `check` selects the foreign-key declaration and its keys.
 */
function validateConstraintTarget(
	change: SchemaChange,
): ValidateConstraintTarget {
	const meta = change.meta;
	if (meta?.check !== undefined)
		return {
			kind: 'check',
			check: requiredRecord(meta.check, change.kind),
		};
	const fk = requiredRecord(meta?.fk, change.kind);
	const references = requiredRecord(fk.references, change.kind);
	requiredColumnList(fk.columns, `${change.kind} columns`);
	requiredColumnList(references.columns, `${change.kind} references.columns`);
	return { kind: 'foreign-key', fk, references };
}

/**
 * Reject malformed key-column lists before any change-specific consumer can
 * derive an address, name, or postcondition from them.
 */
function validateChangeKeyLists(change: SchemaChange): void {
	const meta = change.meta;
	const foreignKey = () => {
		const fk = requiredRecord(meta?.fk, change.kind);
		const references = requiredRecord(fk.references, change.kind);
		requiredColumnList(fk.columns, `${change.kind} columns`);
		requiredColumnList(references.columns, `${change.kind} references.columns`);
	};
	switch (change.kind) {
		case 'create_table':
		case 'readdress_table': {
			const table = meta?.table;
			if (!table || typeof table !== 'object' || Array.isArray(table)) return;
			const primaryKey = (table as Record<string, unknown>).primaryKey;
			if (primaryKey === undefined) return;
			requiredColumnList(
				typeof primaryKey === 'string' ? [primaryKey] : primaryKey,
				`${change.kind} table.primaryKey`,
			);
			return;
		}
		case 'add_primary_key':
		case 'drop_primary_key':
			requiredColumnList(meta?.columns, `${change.kind} columns`);
			return;
		case 'add_foreign_key':
		case 'drop_foreign_key':
		case 'alter_foreign_key':
			foreignKey();
			return;
		case 'validate_constraint':
			validateConstraintTarget(change);
			return;
		default:
			return;
	}
}

function constraintPostcondition(
	change: SchemaChange,
	schema: string,
): GeneratedConstraintPostcondition {
	const meta = change.meta;
	if (change.kind === 'add_primary_key')
		return {
			type: 'p',
			columns: requiredColumnList(meta?.columns, `${change.kind} columns`),
			deferrable: false,
			initiallyDeferred: false,
			enforced: true,
		};
	if (change.kind === 'alter_column_unique')
		return {
			type: 'u',
			columns: [text(change.column, change.kind)],
			deferrable: false,
			initiallyDeferred: false,
			enforced: true,
		};
	const target =
		change.kind === 'validate_constraint'
			? validateConstraintTarget(change)
			: undefined;
	const check = target?.kind === 'check' ? target.check : meta?.check;
	if (check !== undefined) {
		const value = requiredRecord(check, change.kind);
		const expression = text(value.expression, change.kind);
		if (value.notValid !== undefined && typeof value.notValid !== 'boolean')
			throw new Error(
				`generator planning refuses ${change.kind}: invalid typed CHECK notValid state`,
			);
		const state = splitCheckConstraintState({
			expression,
			...(value.notValid === undefined ? {} : { notValid: value.notValid }),
		});
		return {
			type: 'c',
			expression: state.expression,
			notValid: state.notValid,
		};
	}
	const fk =
		target?.kind === 'foreign-key'
			? target.fk
			: requiredRecord(meta?.fk, change.kind);
	const references =
		target?.kind === 'foreign-key'
			? target.references
			: requiredRecord(fk.references, change.kind);
	const foreignKeyAction = (value: unknown): GeneratedForeignKeyAction => {
		const action = typeof value === 'string' ? value : 'NO ACTION';
		if (
			action !== 'NO ACTION' &&
			action !== 'RESTRICT' &&
			action !== 'CASCADE' &&
			action !== 'SET NULL' &&
			action !== 'SET DEFAULT'
		)
			throw new Error(
				`generator planning refuses ${change.kind}: unsupported foreign-key action ${JSON.stringify(action)}`,
			);
		return action;
	};
	return {
		type: 'f',
		columns: requiredColumnList(fk.columns, `${change.kind} columns`),
		references: {
			schema:
				typeof references.schema === 'string' ? references.schema : schema,
			table: text(references.table, change.kind),
			columns: requiredColumnList(
				references.columns,
				`${change.kind} references.columns`,
			),
		},
		onDelete: foreignKeyAction(fk.onDelete),
		onUpdate: foreignKeyAction(fk.onUpdate),
		deferrable: fk.deferred === true,
		initiallyDeferred: fk.deferred === true,
		enforced: true,
		notValid: fk.notValid === true,
	};
}

/**
 * Capture the ModelIR/SchemaChange shape that the executor must read back.
 * This is deliberately assembled before SQL rendering becomes the only durable
 * source, and is therefore covered by the normalized managed-step digest.
 */
export function generatedPostconditionForChange(input: {
	readonly change: SchemaChange;
	readonly schema: string;
}): import('@dbsp/types').LedgerPayload | undefined {
	const { change, schema } = input;
	validateChangeKeyLists(change);
	if (change.kind === 'create_table' || change.kind === 'readdress_table') {
		const table = change.meta?.table;
		if (!table || typeof table !== 'object' || Array.isArray(table))
			throw new Error(
				`generator planning refuses ${change.kind}: missing typed table postcondition`,
			);
		const shape = table as import('@dbsp/types').TableIR;
		const primaryKey = new Set(
			shape.primaryKey === undefined
				? []
				: typeof shape.primaryKey === 'string'
					? [shape.primaryKey]
					: shape.primaryKey,
		);
		return v3Payload({
			canonicalFormVersion: 1,
			kind: 'table',
			columns: shape.columns.map((column) => ({
				name: column.name,
				...columnDeclaration(column, schema, primaryKey.has(column.name)),
			})),
		});
	}
	const column =
		change.kind === 'add_column'
			? requiredColumn(change.meta?.column, change.kind)
			: change.kind === 'alter_column_type' && change.meta?.column !== undefined
				? requiredColumn(change.meta.column, change.kind)
				: (change.kind === 'alter_column_collation' ||
							change.kind === 'alter_column_identity') &&
						change.meta?.column !== undefined
					? requiredColumn(change.meta.column, change.kind)
					: undefined;
	if (column) {
		return v3Payload({
			canonicalFormVersion: 1,
			kind: 'column',
			column: columnDeclaration(column, schema),
		});
	}
	if (change.kind === 'alter_column_type') {
		throw new Error(
			'generator planning refuses alter_column_type: missing typed target column postcondition',
		);
	}
	if (change.kind === 'alter_column_nullable') {
		const name = text(change.column, change.kind);
		const nullable = change.meta?.nullable;
		if (typeof nullable !== 'boolean')
			throw new Error(
				'generator planning refuses alter_column_nullable: missing typed nullable postcondition',
			);
		void name;
		return v3Payload({
			canonicalFormVersion: 1,
			kind: 'column',
			column: { nullable },
		});
	}
	if (change.kind === 'alter_column_default') {
		const name = text(change.column, change.kind);
		const hasDefault = change.meta?.default !== undefined;
		void name;
		return v3Payload({
			canonicalFormVersion: 1,
			kind: 'column',
			column: {
				default: hasDefault
					? {
							defaultKind: 'authored',
							hasDefault: true,
							identity: null,
							defaultExpression: canonicalSqlFact(
								formatSqlDefault(
									change.meta?.default,
									'generator postcondition',
								),
							),
						}
					: { defaultKind: 'none', hasDefault: false, identity: null },
			},
		});
	}
	if (
		change.kind === 'add_primary_key' ||
		change.kind === 'add_foreign_key' ||
		change.kind === 'alter_foreign_key' ||
		change.kind === 'validate_constraint' ||
		change.kind === 'add_check_constraint' ||
		(change.kind === 'alter_column_unique' && change.destructive !== true)
	) {
		const constraint = constraintPostcondition(change, schema);
		return constraint.type === 'c'
			? v3Payload({
					canonicalFormVersion: 1,
					kind: 'check',
					check: {
						expression: canonicalSqlFact(constraint.expression),
						notValid: constraint.notValid,
					},
				})
			: v3Payload({
					canonicalFormVersion: 1,
					kind: 'constraint',
					constraint,
				});
	}
	if (change.kind === 'create_index') {
		const index = change.meta?.index as
			| import('@dbsp/types').IndexIR
			| undefined;
		if (!index)
			throw new Error(
				'generator planning refuses create_index: missing typed index postcondition',
			);
		if (
			index.opclass !== undefined &&
			Object.keys(index.opclass).some(
				(column) => !index.columns.includes(column),
			)
		)
			throw new Error(
				'generator planning refuses create_index: opclass keys must name emitted columns',
			);
		return v3Payload({
			canonicalFormVersion: 1,
			kind: 'index',
			index: {
				method: index.method ?? 'btree',
				unique: index.unique === true,
				valid: true,
				ready: true,
				live: true,
				columns: index.columns,
				...(index.expressions === undefined
					? {}
					: {
							expressions: index.expressions.map(canonicalSqlFact),
						}),
				...(index.include === undefined ? {} : { include: index.include }),
				nullsNotDistinct: index.nullsNotDistinct === true,
				...(index.opclass === undefined ? {} : { opclass: index.opclass }),
				...(index.with === undefined ? {} : { with: index.with }),
				...(index.where === undefined
					? {}
					: { where: canonicalSqlFact(index.where) }),
			},
		});
	}
	if (change.kind === 'create_enum' || change.kind === 'alter_enum_add_value') {
		const enumDef = requiredRecord(change.meta?.enum, change.kind);
		return v3Payload({
			canonicalFormVersion: 1,
			kind: 'enum',
			labels: requiredList(enumDef.values, change.kind),
		});
	}
	if (change.kind === 'create_sequence' || change.kind === 'alter_sequence') {
		const sequence = requiredRecord(change.meta?.sequence, change.kind);
		const numberProperty = (name: string): string | undefined =>
			typeof sequence[name] === 'number' ? String(sequence[name]) : undefined;
		const startValue = numberProperty('startWith');
		const incrementBy = numberProperty('incrementBy');
		const minValue = numberProperty('minValue');
		const maxValue = numberProperty('maxValue');
		return v3Payload({
			canonicalFormVersion: 1,
			kind: 'sequence',
			...(startValue === undefined ? {} : { startValue }),
			...(incrementBy === undefined ? {} : { incrementBy }),
			...(minValue === undefined ? {} : { minValue }),
			...(maxValue === undefined ? {} : { maxValue }),
			...(typeof sequence.cycle === 'boolean' ? { cycle: sequence.cycle } : {}),
		});
	}
	if (change.kind === 'create_extension') {
		const version = change.meta?.extensionVersion;
		if (version !== undefined && typeof version !== 'string')
			throw new Error(
				'generator planning refuses create_extension: invalid typed extension version',
			);
		return v3Payload({
			canonicalFormVersion: 1,
			kind: 'extension',
			...(typeof version === 'string' ? { version } : {}),
		});
	}
	if (
		change.kind === 'drop_table' ||
		change.kind === 'drop_column' ||
		change.kind === 'drop_primary_key' ||
		change.kind === 'drop_foreign_key' ||
		change.kind === 'drop_index' ||
		change.kind === 'drop_check_constraint' ||
		change.kind === 'drop_enum' ||
		change.kind === 'drop_extension' ||
		change.kind === 'drop_sequence' ||
		(change.kind === 'alter_column_unique' && change.destructive === true)
	)
		return v3Payload({ canonicalFormVersion: 1, kind: 'absent' });
	throw new Error(
		`generator planning refuses ${change.kind}: no typed postcondition is available`,
	);
}

/**
 * The only change-kind boundary between diagnostic schema diffing and managed
 * execution.  Keep it at manifest construction: diagnostic-only controls must
 * never acquire an address, claim, reservation, or DDL bundle.
 */
export function assertDeclarableChangeKind(
	kind: ChangeKind,
): asserts kind is Exclude<
	ChangeKind,
	| 'enable_rls'
	| 'disable_rls'
	| 'create_policy'
	| 'drop_policy'
	| 'add_comment'
	| 'drop_comment'
> {
	switch (kind) {
		case 'enable_rls':
		case 'disable_rls':
		case 'create_policy':
		case 'drop_policy':
		case 'add_comment':
		case 'drop_comment':
			throw new Error(
				`generator planning refuses ${kind}: it is diagnostic-only and non-declarable`,
			);
		case 'create_table':
		case 'drop_table':
		case 'readdress_table':
		case 'add_column':
		case 'drop_column':
		case 'alter_column_type':
		case 'alter_column_nullable':
		case 'alter_column_default':
		case 'alter_column_unique':
		case 'add_primary_key':
		case 'drop_primary_key':
		case 'add_foreign_key':
		case 'drop_foreign_key':
		case 'alter_foreign_key':
		case 'validate_constraint':
		case 'create_index':
		case 'drop_index':
		case 'add_check_constraint':
		case 'drop_check_constraint':
		case 'create_enum':
		case 'alter_enum_add_value':
		case 'drop_enum':
		case 'alter_column_collation':
		case 'alter_column_identity':
		case 'create_extension':
		case 'drop_extension':
		case 'create_sequence':
		case 'alter_sequence':
		case 'drop_sequence':
			return;
	}
}

function text(value: unknown, label: string): string {
	if (typeof value !== 'string' || value.length === 0)
		throw new Error(`generator planning refuses ${label}: missing typed name`);
	return value;
}

function stringList(value: unknown, label: string): readonly string[] {
	if (
		!Array.isArray(value) ||
		value.length === 0 ||
		value.some((item) => typeof item !== 'string' || item.trim().length === 0)
	)
		throw new Error(
			`generator planning refuses ${label}: missing typed columns`,
		);
	return value as readonly string[];
}

function named(meta: Meta | undefined, key: string, label: string): string {
	return text(meta?.[key], label);
}

function nestedName(
	meta: Meta | undefined,
	key: string,
	label: string,
): string {
	const item = meta?.[key];
	if (!item || typeof item !== 'object' || Array.isArray(item))
		throw new Error(
			`generator planning refuses ${label}: missing typed ${key}`,
		);
	return text((item as Record<string, unknown>).name, label);
}

function tableAddress(
	database: string,
	schema: string,
	table: string,
): Address {
	return {
		scope: 'schema',
		engine: 'postgresql',
		database,
		schema,
		kind: 'table',
		name: table,
	};
}

function childAddress(
	database: string,
	schema: string,
	kind: Extract<Address['kind'], 'column' | 'index' | 'constraint'>,
	name: string,
	table: string,
): Address {
	return {
		scope: 'schema',
		engine: 'postgresql',
		database,
		schema,
		kind,
		name,
		parent: canonicalResourceParent(tableAddress(database, schema, table)),
	};
}

export function addressForChange(input: {
	readonly change: SchemaChange;
	readonly database: string;
	readonly schema: string;
}): Address {
	const { change, database, schema } = input;
	const meta = change.meta;
	const column = () =>
		childAddress(
			database,
			schema,
			'column',
			text(change.column, change.kind),
			change.table,
		);
	const constraint = (name: string) =>
		childAddress(database, schema, 'constraint', name, change.table);
	const fkName = (fk: Readonly<Record<string, unknown>>) => {
		return `fk_${change.table}_${stringList(fk.columns, `${change.kind} columns`).join('_')}`;
	};
	switch (change.kind) {
		case 'create_table':
		case 'drop_table':
		case 'readdress_table':
		case 'enable_rls':
		case 'disable_rls':
			return tableAddress(database, schema, change.table);
		case 'add_column':
		case 'drop_column':
		case 'alter_column_type':
		case 'alter_column_nullable':
		case 'alter_column_default':
		case 'alter_column_collation':
		case 'alter_column_identity':
			return column();
		case 'alter_column_unique':
			return constraint(
				text(
					meta?.constraintName ??
						`${change.table}_${text(change.column, change.kind)}_key`,
					change.kind,
				),
			);
		case 'add_primary_key':
		case 'drop_primary_key':
			return constraint(`pk_${change.table}`);
		case 'add_foreign_key':
		case 'drop_foreign_key':
		case 'alter_foreign_key':
			return constraint(fkName(requiredRecord(meta?.fk, change.kind)));
		case 'validate_constraint': {
			const target = validateConstraintTarget(change);
			return constraint(
				target.kind === 'check'
					? text(target.check.name, change.kind)
					: fkName(target.fk),
			);
		}
		case 'create_index':
		case 'drop_index': {
			const index = meta?.index;
			if (!index || typeof index !== 'object' || Array.isArray(index))
				throw new Error(
					`generator planning refuses ${change.kind}: missing typed index`,
				);
			const record = index as Record<string, unknown>;
			const name =
				typeof record.name === 'string' && record.name.length > 0
					? record.name
					: `idx_${change.table}_${stringList(record.columns, change.kind).join('_')}`;
			return childAddress(database, schema, 'index', name, change.table);
		}
		case 'add_check_constraint':
		case 'drop_check_constraint':
			return constraint(nestedName(meta, 'check', change.kind));
		case 'create_enum':
		case 'alter_enum_add_value':
		case 'drop_enum':
			return {
				scope: 'schema',
				engine: 'postgresql',
				database,
				schema,
				kind: 'enum',
				name: nestedName(meta, 'enum', change.kind),
			};
		case 'create_extension':
		case 'drop_extension':
			return {
				scope: 'database',
				engine: 'postgresql',
				database,
				kind: 'extension',
				name: named(meta, 'extension', change.kind),
			};
		case 'create_sequence':
		case 'alter_sequence':
		case 'drop_sequence':
			return {
				scope: 'schema',
				engine: 'postgresql',
				database,
				schema,
				kind: 'sequence',
				name: nestedName(meta, 'sequence', change.kind),
			};
		case 'add_comment':
		case 'drop_comment':
		case 'create_policy':
		case 'drop_policy':
			throw new Error(
				`generator planning refuses ${change.kind}: it is diagnostic-only and non-declarable`,
			);
		default: {
			const exhaustive: never = change.kind;
			throw new Error(
				`generator planning refuses unsupported change kind ${exhaustive}`,
			);
		}
	}
}

function createsAddress(change: SchemaChange): boolean {
	if (change.kind === 'alter_column_unique') return change.destructive !== true;
	return new Set<ChangeKind>([
		'create_table',
		'add_column',
		'add_primary_key',
		'add_foreign_key',
		'create_index',
		'add_check_constraint',
		'create_enum',
		'create_extension',
		'create_sequence',
	]).has(change.kind);
}

/**
 * PostgreSQL's total ChangeKind-to-address producer.  The mapping is run at
 * plan time, so no executable generator step can later fall through to a
 * permissive "no managed address" branch.
 */
export function createPgsqlGeneratedManagedStep(input: {
	readonly change: SchemaChange;
	readonly database: string;
	readonly schema: string;
	readonly stepKey: string;
	readonly order: number;
	readonly dependencyOrder?: readonly string[];
	readonly statements: readonly string[];
}): NormalizedManagedStep {
	validateChangeKeyLists(input.change);
	assertDeclarableChangeKind(input.change.kind);
	const address = addressForChange(input);
	if (input.statements.length === 0 && input.change.kind !== 'readdress_table')
		throw new Error(
			`generator planning refuses ${input.change.kind}: adapter produced an empty statement bundle`,
		);
	const classification: GeneratedMutationClassification =
		classifyGeneratedMutation(input.change.kind, input.change);
	const claimKind: LedgerClaimKind =
		classification === 'removal'
			? 'retire-intent'
			: classification === 'paired-readdress'
				? 'readdress-intent'
				: 'intent';
	const expectedDeclaration = generatedPostconditionForChange({
		change: input.change,
		schema: input.schema,
	});
	return {
		stepKey: input.stepKey,
		order: input.order,
		segmentId: `generator-segment-${input.order}`,
		dependencyOrder: input.dependencyOrder ?? [],
		address,
		claimKind,
		plannedClaimKeys: [`${input.stepKey}:root`],
		statementBundle: {
			statements: input.statements.map((sql, ordinal) => ({ ordinal, sql })),
		},
		classification,
		requiresVacancy: createsAddress(input.change),
		...(expectedDeclaration === undefined ? {} : { expectedDeclaration }),
		replayPolicy: classification === 'removal' ? 'fresh-live-only' : 'recorded',
	};
}
