/**
 * Tests for Migration File Format v2 — UP + DOWN sections.
 */

import { describe, expect, it, vi } from 'vitest';
import {
	generateMigrationFile,
	isDestructiveDown,
	parseMigrationFile,
} from './migration-file.js';
import type { SchemaDiff } from './schema-diff.js';

// ============================================================================
// Helpers
// ============================================================================

function makeDiff(): SchemaDiff {
	// We mock generateMigrationSQL and generateDownSQL via vi.mock,
	// so the diff object just needs to satisfy the type.
	return {
		changes: [],
		hasDestructive: false,
		summary: {
			tables: { added: 0, dropped: 0 },
			columns: { added: 0, dropped: 0, altered: 0 },
			indexes: { added: 0, dropped: 0 },
			constraints: { added: 0, dropped: 0, altered: 0 },
		},
	} as SchemaDiff;
}

// ============================================================================
// Mock migration-sql to control UP/DOWN output
// ============================================================================

vi.mock('./migration-sql.js', () => ({
	generateMigrationSQL: vi.fn(),
	generateDownSQL: vi.fn(),
}));

// Re-import as mocks
import { generateDownSQL, generateMigrationSQL } from './migration-sql.js';

const mockGenerateMigrationSQL = vi.mocked(generateMigrationSQL);
const mockGenerateDownSQL = vi.mocked(generateDownSQL);

// ============================================================================
// generateMigrationFile
// ============================================================================

describe('generateMigrationFile', () => {
	it('SC-09: should generate file with UP + DOWN sections', () => {
		// Arrange
		const diff = makeDiff();
		mockGenerateMigrationSQL.mockReturnValue([
			'CREATE TABLE "users" ("id" serial PRIMARY KEY)',
			'ALTER TABLE "users" ADD COLUMN "name" text',
		]);
		mockGenerateDownSQL.mockReturnValue([
			'ALTER TABLE "users" DROP COLUMN "name" CASCADE',
			'DROP TABLE IF EXISTS "users" CASCADE',
		]);

		// Act
		const result = generateMigrationFile(diff);

		// Assert
		expect(result).toContain('CREATE TABLE "users" ("id" serial PRIMARY KEY)');
		expect(result).toContain('-- DOWN');
		expect(result).toContain('DROP TABLE IF EXISTS "users" CASCADE');

		// Verify separator is on its own line
		const lines = result.split('\n');
		const downLine = lines.find((l) => l.trim() === '-- DOWN');
		expect(downLine).toBeDefined();
	});

	it('should include migration name in header when provided', () => {
		// Arrange
		const diff = makeDiff();
		mockGenerateMigrationSQL.mockReturnValue([
			'CREATE TABLE "t" ("id" serial)',
		]);
		mockGenerateDownSQL.mockReturnValue(['DROP TABLE IF EXISTS "t" CASCADE']);

		// Act
		const result = generateMigrationFile(diff, { name: '0001_create_users' });

		// Assert
		expect(result).toContain('-- Migration: 0001_create_users');
		expect(result).toContain('-- Generated by: dbsp migrate dev');
		expect(result).toContain('-- Date: ');
	});

	it('should handle empty diff (no statements)', () => {
		// Arrange
		const diff = makeDiff();
		mockGenerateMigrationSQL.mockReturnValue([]);
		mockGenerateDownSQL.mockReturnValue([]);

		// Act
		const result = generateMigrationFile(diff);

		// Assert — should still have the separator
		expect(result).toContain('-- DOWN');
		// Only whitespace around the separator
		expect(result.trim()).toBe('-- DOWN');
	});
});

// ============================================================================
// parseMigrationFile
// ============================================================================

describe('parseMigrationFile', () => {
	it('should parse file with UP and DOWN sections', () => {
		// Arrange
		const content = [
			'CREATE TABLE "users" ("id" serial PRIMARY KEY);',
			'',
			'ALTER TABLE "users" ADD COLUMN "name" text;',
			'',
			'-- DOWN',
			'',
			'ALTER TABLE "users" DROP COLUMN "name" CASCADE;',
			'',
			'DROP TABLE IF EXISTS "users" CASCADE;',
			'',
		].join('\n');

		// Act
		const result = parseMigrationFile(content);

		// Assert
		expect(result.hasDown).toBe(true);
		expect(result.upStatements).toHaveLength(2);
		expect(result.upStatements[0]).toContain('CREATE TABLE "users"');
		expect(result.upStatements[1]).toContain('ALTER TABLE "users" ADD COLUMN');
		expect(result.downStatements).toHaveLength(2);
		expect(result.downStatements[0]).toContain('DROP COLUMN "name"');
		expect(result.downStatements[1]).toContain('DROP TABLE IF EXISTS "users"');
	});

	it('SC-10: should return hasDown=false when no separator exists', () => {
		// Arrange — legacy v1 migration file (no DOWN section)
		const content = [
			'CREATE TABLE "users" ("id" serial PRIMARY KEY);',
			'',
			'ALTER TABLE "users" ADD COLUMN "name" text;',
			'',
		].join('\n');

		// Act
		const result = parseMigrationFile(content);

		// Assert
		expect(result.hasDown).toBe(false);
		expect(result.upStatements).toHaveLength(2);
		expect(result.downStatements).toHaveLength(0);
	});

	it('SC-11: should return empty downStatements when DOWN section is empty', () => {
		// Arrange
		const content = [
			'CREATE TABLE "users" ("id" serial PRIMARY KEY);',
			'',
			'-- DOWN',
			'',
		].join('\n');

		// Act
		const result = parseMigrationFile(content);

		// Assert
		expect(result.hasDown).toBe(true);
		expect(result.upStatements).toHaveLength(1);
		expect(result.downStatements).toHaveLength(0);
	});

	it('SC-25: separator inside SQL string does not split', () => {
		// Arrange — `-- DOWN` is part of a SQL string value, not on its own line
		const content = [
			'INSERT INTO "metadata" ("key", "value") VALUES (\'marker\', \'-- DOWN\');',
			'',
			'-- DOWN',
			'',
			'DELETE FROM "metadata" WHERE "key" = \'marker\';',
			'',
		].join('\n');

		// Act
		const result = parseMigrationFile(content);

		// Assert — should correctly identify the real separator
		expect(result.hasDown).toBe(true);
		expect(result.upStatements).toHaveLength(1);
		expect(result.upStatements[0]).toContain('INSERT INTO "metadata"');
		expect(result.downStatements).toHaveLength(1);
		expect(result.downStatements[0]).toContain('DELETE FROM "metadata"');
	});

	it('should handle multiple statements in each section', () => {
		// Arrange
		const content = [
			'CREATE TABLE "a" ("id" serial);',
			'',
			'CREATE TABLE "b" ("id" serial);',
			'',
			'CREATE INDEX "idx_a" ON "a" ("id");',
			'',
			'-- DOWN',
			'',
			'DROP INDEX IF EXISTS "idx_a";',
			'',
			'DROP TABLE IF EXISTS "b" CASCADE;',
			'',
			'DROP TABLE IF EXISTS "a" CASCADE;',
			'',
		].join('\n');

		// Act
		const result = parseMigrationFile(content);

		// Assert
		expect(result.hasDown).toBe(true);
		expect(result.upStatements).toHaveLength(3);
		expect(result.downStatements).toHaveLength(3);
	});

	it('should handle header comments in migration files', () => {
		// Arrange
		const content = [
			'-- Migration: 0001_init',
			'-- Generated by: dbsp migrate dev',
			'-- Date: 2026-02-16T10:00:00.000Z',
			'',
			'CREATE TABLE "users" ("id" serial PRIMARY KEY);',
			'',
			'-- DOWN',
			'',
			'DROP TABLE IF EXISTS "users" CASCADE;',
			'',
		].join('\n');

		// Act
		const result = parseMigrationFile(content);

		// Assert
		expect(result.hasDown).toBe(true);
		// Header comments become part of the first UP statement after split
		expect(result.upStatements.length).toBeGreaterThanOrEqual(1);
		expect(result.downStatements).toHaveLength(1);
	});
});

// ============================================================================
// isDestructiveDown
// ============================================================================

describe('isDestructiveDown', () => {
	it('should detect DROP TABLE', () => {
		const stmts = ['DROP TABLE IF EXISTS "users" CASCADE'];
		expect(isDestructiveDown(stmts)).toBe(true);
	});

	it('should detect DROP COLUMN', () => {
		const stmts = ['ALTER TABLE "users" DROP COLUMN "email" CASCADE'];
		expect(isDestructiveDown(stmts)).toBe(true);
	});

	it('should detect ALTER COLUMN TYPE (lossy type change)', () => {
		const stmts = ['ALTER TABLE "users" ALTER COLUMN "age" TYPE smallint'];
		expect(isDestructiveDown(stmts)).toBe(true);
	});

	it('should return false for non-destructive statements', () => {
		const stmts = [
			'CREATE TABLE "users" ("id" serial)',
			'ALTER TABLE "users" ADD COLUMN "name" text',
			'CREATE INDEX "idx_name" ON "users" ("name")',
		];
		expect(isDestructiveDown(stmts)).toBe(false);
	});

	it('should return false for empty array', () => {
		expect(isDestructiveDown([])).toBe(false);
	});

	it('should detect case-insensitive patterns', () => {
		const stmts = ['drop table if exists "users" cascade'];
		expect(isDestructiveDown(stmts)).toBe(true);
	});

	it('should handle WARNING comments alongside destructive statements', () => {
		const stmts = [
			'-- WARNING: Cannot reverse create_table "users" — table data was lost',
			'DROP TABLE IF EXISTS "legacy" CASCADE',
		];
		expect(isDestructiveDown(stmts)).toBe(true);
	});
});
