/**
 * Migration File Format — UP + DOWN sections.
 *
 * File format:
 *   -- dbsp:destructive: true|false
 *   <UP statements>;
 *   -- DOWN
 *   <DOWN statements>;
 *
 * The separator `-- DOWN` must be on its own line (SC-25).
 *
 * @module ddl/migration-file
 */

import type { MigrationSQLOptions } from './migration-sql.js';
import {
	type CompiledMigration,
	compileMigration,
	MigrationPhaseBoundaryError,
} from './migration-sql.js';
import { isRenderableEnumLabel } from './phases/utils.js';
import type { SchemaDiff } from './schema-diff.js';

/**
 * Result of parsing a migration file's UP/DOWN sections.
 */
export interface ParsedMigrationFile {
	/** Legacy flattened UP view, retained for programmatic compatibility. */
	readonly upStatements: readonly string[];
	readonly downStatements: readonly string[];
	readonly hasDown: boolean;
	readonly destructive?: boolean | undefined;
}

/** Main migration content and its optional enum-autocommit sidecar. */
export interface PhasedMigrationFiles {
	readonly content: string;
	readonly preContent?: string;
}

/**
 * Generate a migration file content with UP and DOWN sections.
 */
// v4 (#389): remove — kept exported only because deleting a public export is a
// major. Callers want generatePhasedMigrationFiles(), which keeps the sidecar.
export function generateMigrationFile(
	diff: SchemaDiff,
	options?: MigrationSQLOptions & { name?: string },
): string {
	const files = generatePhasedMigrationFiles(diff, options);
	if (files.preContent !== undefined) {
		throw new MigrationPhaseBoundaryError('generateMigrationFile');
	}
	return files.content;
}

/** Generate both artifacts without flattening the PostgreSQL phase boundary. */
export function generatePhasedMigrationFiles(
	diff: SchemaDiff,
	options?: MigrationSQLOptions & { name?: string },
): PhasedMigrationFiles {
	return renderPhasedMigrationFiles(compileMigration(diff, options), options);
}

/** Render file artifacts from one already-compiled snapshot. */
export function renderPhasedMigrationFiles(
	compiled: CompiledMigration,
	options?: MigrationSQLOptions & { name?: string },
): PhasedMigrationFiles {
	const downStatements = compiled.down.statements;
	const destructiveHeader = `-- dbsp:destructive: ${compiled.down.destructive ? 'true' : 'false'}`;

	const header = options?.name
		? `-- Migration: ${options.name}\n-- Generated by: dbsp migrate dev\n-- Date: ${new Date().toISOString()}\n${destructiveHeader}\n\n`
		: `${destructiveHeader}\n\n`;

	const upSection = renderStatements(compiled.plan.main);
	const downSection =
		downStatements.length > 0 ? `${downStatements.join(';\n\n')};\n` : '';

	const separatorPrefix = upSection.length > 0 ? '\n' : '';

	const content = `${header}${upSection}${separatorPrefix}-- DOWN\n\n${downSection}`;
	return {
		content,
		...(compiled.plan.autocommit.length > 0
			? { preContent: `${compiled.plan.autocommit.join('\n')}\n` }
			: {}),
	};
}

function renderStatements(statements: readonly string[]): string {
	return statements.length > 0 ? `${statements.join(';\n\n')};\n` : '';
}

/**
 * Parse a migration file into UP and DOWN sections.
 * Separator: `^\s*-- DOWN\s*$` (strict regex, own line only — SC-25)
 */
export function parseMigrationFile(content: string): ParsedMigrationFile {
	const destructive = parseDestructiveHeader(content);
	// Strict regex: -- DOWN must be on its own line
	const separatorRegex = /^\s*-- DOWN\s*$/m;
	const match = separatorRegex.exec(content);

	if (!match) {
		// No DOWN section — legacy v1 file
		return {
			upStatements: splitStatements(content),
			downStatements: [],
			hasDown: false,
			destructive,
		};
	}

	const upContent = content.slice(0, match.index);
	const downContent = content.slice(match.index + match[0].length);

	return {
		upStatements: splitStatements(upContent),
		downStatements: splitStatements(downContent),
		hasDown: true,
		destructive,
	};
}

function parseDestructiveHeader(content: string): boolean | undefined {
	let destructive: boolean | undefined;
	let found = false;

	for (const line of content.split(/\r?\n/)) {
		const trimmed = line.trim();
		if (trimmed.length === 0) {
			continue;
		}
		if (/^--\s*DOWN\s*$/i.test(trimmed)) {
			break;
		}
		if (!trimmed.startsWith('--')) {
			break;
		}

		const match = /^--\s*dbsp:destructive:\s*(true|false)\s*$/i.exec(trimmed);
		if (!match) {
			continue;
		}
		if (found) {
			return undefined;
		}
		found = true;
		destructive = match[1]?.toLowerCase() === 'true';
	}

	return found ? destructive : undefined;
}

/**
 * Check if SQL statements contain destructive operations.
 * Destructive: DROP TABLE, DROP COLUMN, lossy ALTER COLUMN TYPE
 */
export function isDestructiveDown(downStatements: readonly string[]): boolean {
	const destructivePatterns = [
		/DROP\s+TABLE/i,
		/DROP\s+COLUMN/i,
		/ALTER\s+COLUMN\s+\S+\s+TYPE/i, // lossy type change
	];

	return downStatements.some((stmt) =>
		destructivePatterns.some((pattern) => pattern.test(stmt)),
	);
}

/**
 * Split SQL content into individual statements by semicolons.
 * Filters out empty strings. Preserves WARNING comments.
 */
function splitStatements(content: string): string[] {
	return content
		.split(/;\s*\n/)
		.map((s) => s.trim())
		.filter((s) => s.length > 0);
}

const COMMENT_ONLY_SQL = /^(?:\s*--[^\n]*(?:\n|$))*\s*$/;

/** Whether statements contain SQL beyond preserved line comments. */
export function hasExecutableSqlStatements(
	statements: readonly string[],
): boolean {
	return statements.some((statement) => !COMMENT_ONLY_SQL.test(statement));
}

/**
 * Parse a generated enum-autocommit sidecar. This deliberately accepts only
 * dbsp's renderer spelling, not every PostgreSQL spelling of ALTER TYPE.
 * Hand-written sidecars in another spelling are rejected so they cannot become
 * an untransactional arbitrary-SQL escape hatch.
 */
export function parseEnumAdditionSidecar(content: string): readonly string[] {
	const statements = splitSidecarStatements(content);
	for (const statement of statements) {
		if (!isCanonicalEnumAddition(statement)) {
			throw new Error(
				'Invalid enum sidecar: expected dbsp-rendered ALTER TYPE ... ADD VALUE IF NOT EXISTS statement.',
			);
		}
	}
	return statements;
}

/**
 * The general migration parser consumes statement delimiters because callers
 * execute its fragments independently. The sidecar whitelist instead compares
 * against renderer output, which includes trailing semicolons, so retain them
 * here to make that round trip exact.
 */
function splitSidecarStatements(content: string): string[] {
	return content
		.split(/(?<=;)\s*\n/)
		.map((statement) => statement.trim())
		.filter((statement) => statement.length > 0);
}

function isCanonicalEnumAddition(statement: string): boolean {
	const identifier = '"[A-Za-z_][A-Za-z0-9_$]*"';
	const qualifiedType = `(?:${identifier}|${identifier}\\.${identifier})`;
	const quotedLabel = "'((?:[^'\\\\\\n\\r]|'')*)'";
	const match = new RegExp(
		`^ALTER TYPE ${qualifiedType} ADD VALUE IF NOT EXISTS ${quotedLabel}(?: AFTER ${quotedLabel})?;$`,
	).exec(statement);
	return (
		match !== null &&
		isRenderableEnumLabel(match[1]!.replace(/''/g, "'")) &&
		(match[2] === undefined ||
			isRenderableEnumLabel(match[2].replace(/''/g, "'")))
	);
}
