/**
 * Migration File Format v2 — UP + DOWN sections.
 *
 * File format:
 *   -- dbsp:destructive: true|false
 *   <UP statements>;
 *   -- DOWN
 *   <DOWN statements>;
 *
 * The separator `-- DOWN` must be on its own line (SC-25).
 *
 * @module ddl/migration-file
 */

import type { MigrationSQLOptions } from './migration-sql.js';
import {
	generateDownMigrationSQL,
	generateMigrationSQL,
} from './migration-sql.js';
import type { SchemaDiff } from './schema-diff.js';

/**
 * Result of parsing a migration file's UP/DOWN sections.
 */
export interface ParsedMigrationFile {
	readonly upStatements: readonly string[];
	readonly downStatements: readonly string[];
	readonly hasDown: boolean;
	readonly destructive?: boolean | undefined;
}

/**
 * Generate a migration file content with UP and DOWN sections.
 */
export function generateMigrationFile(
	diff: SchemaDiff,
	options?: MigrationSQLOptions & { name?: string },
): string {
	const upStatements = generateMigrationSQL(diff, options);
	const downMigration = generateDownMigrationSQL(diff, options);
	const downStatements = downMigration.statements;
	const destructiveHeader = `-- dbsp:destructive: ${downMigration.destructive ? 'true' : 'false'}`;

	const header = options?.name
		? `-- Migration: ${options.name}\n-- Generated by: dbsp migrate dev\n-- Date: ${new Date().toISOString()}\n${destructiveHeader}\n\n`
		: `${destructiveHeader}\n\n`;

	const upSection =
		upStatements.length > 0 ? `${upStatements.join(';\n\n')};\n` : '';
	const downSection =
		downStatements.length > 0 ? `${downStatements.join(';\n\n')};\n` : '';

	const separatorPrefix = upSection.length > 0 ? '\n' : '';

	return `${header}${upSection}${separatorPrefix}-- DOWN\n\n${downSection}`;
}

/**
 * Parse a migration file into UP and DOWN sections.
 * Separator: `^\s*-- DOWN\s*$` (strict regex, own line only — SC-25)
 */
export function parseMigrationFile(content: string): ParsedMigrationFile {
	const destructive = parseDestructiveHeader(content);
	// Strict regex: -- DOWN must be on its own line
	const separatorRegex = /^\s*-- DOWN\s*$/m;
	const match = separatorRegex.exec(content);

	if (!match) {
		// No DOWN section — legacy v1 file
		return {
			upStatements: splitStatements(content),
			downStatements: [],
			hasDown: false,
			destructive,
		};
	}

	const upContent = content.slice(0, match.index);
	const downContent = content.slice(match.index + match[0].length);

	return {
		upStatements: splitStatements(upContent),
		downStatements: splitStatements(downContent),
		hasDown: true,
		destructive,
	};
}

function parseDestructiveHeader(content: string): boolean | undefined {
	let destructive: boolean | undefined;
	let found = false;

	for (const line of content.split(/\r?\n/)) {
		const trimmed = line.trim();
		if (trimmed.length === 0) {
			continue;
		}
		if (/^--\s*DOWN\s*$/i.test(trimmed)) {
			break;
		}
		if (!trimmed.startsWith('--')) {
			break;
		}

		const match = /^--\s*dbsp:destructive:\s*(true|false)\s*$/i.exec(trimmed);
		if (!match) {
			continue;
		}
		if (found) {
			return undefined;
		}
		found = true;
		destructive = match[1]?.toLowerCase() === 'true';
	}

	return found ? destructive : undefined;
}

/**
 * Check if SQL statements contain destructive operations.
 * Destructive: DROP TABLE, DROP COLUMN, lossy ALTER COLUMN TYPE
 */
export function isDestructiveDown(downStatements: readonly string[]): boolean {
	const destructivePatterns = [
		/DROP\s+TABLE/i,
		/DROP\s+COLUMN/i,
		/ALTER\s+COLUMN\s+\S+\s+TYPE/i, // lossy type change
	];

	return downStatements.some((stmt) =>
		destructivePatterns.some((pattern) => pattern.test(stmt)),
	);
}

/**
 * Split SQL content into individual statements by semicolons.
 * Filters out empty strings. Preserves WARNING comments.
 */
function splitStatements(content: string): string[] {
	return content
		.split(/;\s*\n/)
		.map((s) => s.trim())
		.filter((s) => s.length > 0);
}
