/**
 * Package-internal managed-outcome authority. This subpath exists solely for
 * the PostgreSQL adapter and CLI orchestration; it is not part of the
 * documented @dbsp/core API.
 */

export {
	type AdapterCapabilities,
	type AdapterStreamOptions,
	type CompileOnlyAdapter,
	type ConnectionAvailability,
	type DumpMeta,
	supportsExecution,
	supportsStreaming,
	supportsTransactions,
	type TransactionOptions,
} from './adapter.js';
// Adapter and CLI implementation surface (issue #860).
export {
	ASSERTION_TYPES,
	type AssertionBlock,
	assertContains,
	assertDbColumnExists,
	assertDbOutput,
	assertDbRowsEquals,
	assertDbRowsMax,
	assertDbRowsMin,
	assertDbValueEquals,
	assertIntentHasGroupBy,
	assertIntentHasOrderBy,
	assertIntentHasWhere,
	assertIntentTable,
	assertIntentType,
	assertIntentWith,
	assertMatches,
	assertParamsLength,
	assertParamsValue,
	assertSQLColumn,
	assertSQLJoin,
	assertSQLTable,
	assertSuccess,
	isOverallSuccess,
	requiresDatabase,
	resolveQueryIndex,
} from './assert/index.js';
export {
	DUCKDB_CAPABILITIES,
	MSSQL_CAPABILITIES,
	MYSQL_CAPABILITIES,
	SQLITE_CAPABILITIES,
} from './dialects/index.js';
export {
	countDistinctRelationPathsByName,
	deriveRelationPathFromIntentPath,
	isExpressionSpec,
	isWhereIntent,
	type OrderByRecord,
	objectToWhereIntent,
	rawNotExists,
	stringAgg,
	validateTypeName,
} from './dx/index.js';
export { type RefDefinition, validateSchemaIndexOptions } from './dx/schema.js';
export {
	type CaseExpressionIntent,
	type DeleteIntent,
	isSubqueryRef,
	type LiteralExpressionIntent,
	type SelectAllIntent,
	type UpdateIntent,
	type UpsertIntent,
	type WhereAnyIntent,
	type WhereExistsIntent,
	type WhereNotExistsIntent,
	type WhereRelationFilterIntent,
	type WhereSubqueryIntent,
} from './intent-ast.js';
export type {
	ColumnJsReadType,
	ForeignKeyIR,
	LogicalIdentity,
	OnDeleteAction,
	PartitionIR,
	RelationIR,
	RelationType,
	RequiredEnumLabelIR,
	TableReaddressDeclaration,
} from './model-ir.js';
export { inspectMutationRows } from './mutation-rows.js';
export {
	normalizeRecursiveIncludeOptions,
	type RecursivePlanReport,
	validateIncludeInput,
	validateIncludeOptions,
	validateIncludeOrdering,
	validateIncludeStrategy,
	validateRecursiveIncludeStrategy,
	validateRecursiveSetOperation,
	validateResolvedIncludeStrategy,
} from './planner.js';
export {
	type AdmittedDestructiveOutcomeClaim,
	admitDestructiveOutcomeClaim,
	attachDestructiveAuthorityPermit,
	decideDestructiveDecision,
	isDestructiveAuthorityPermit,
} from './transition/destructive-authority.js';
export { escapeDiagnosticText } from './transition/diagnostic-text.js';
export {
	type DurablyLoadedRun,
	isDurablyLoadedRun,
	mintDurablyLoadedRun,
} from './transition/durably-loaded-run.js';
export {
	assertDeclaredEnumMapIdentity,
	EnumNameMapKeyMismatchError,
} from './transition/enum-name.js';
export {
	type ApplicableEvaluation,
	type ApplyPolicy,
	acquireExclusiveTransitionLease,
	acquireTransitionLease,
	acquireTransitionTargetLease,
	advisoryObservationId,
	assertCanonicalizableJson,
	assumptionAccepted,
	assumptionId,
	bindDeclarationSet,
	bindExecutionContract,
	type CapabilityDescriptor,
	type CompareOutcome,
	canonicalJson,
	canonicalJsonDigest,
	checkDelta,
	claimId,
	classifyOutcomeRecovery,
	concludeEvidenceForObligation,
	createApplier,
	createComparator,
	createEvidenceView,
	createExclusiveTransitionTarget,
	createExecutionContract,
	createPackRegistry,
	createProver,
	createTransitionLessor,
	createTransitionRunMetadata,
	type DurableIntentRecord,
	declarationSetFromModel,
	defaultIndexName,
	type ExclusiveTransitionTarget,
	type ExecutionCoordinator,
	enumAddDelta,
	evidenceId,
	type FingerprintManifest,
	type InProcessProvenPlan,
	indexDelta,
	isExclusiveTransitionTarget,
	isTransitionLessor,
	loadVerifiedRecoveryJournal,
	type ManagedOutcomeExecutionRequest,
	type ManagedOutcomePreflightRequest,
	type NonRollbackableExecutionTracker,
	normalizedIndex,
	type ObservationContext,
	type ObservationIssuer,
	type ObservationRequest,
	type OperationEffectAssessment,
	observationContextDigest,
	outcomeClaimEventId,
	outcomeClaimId,
	PackRegistry,
	type PhysicalOperation,
	type ProvenPlanShape,
	planOperationSession,
	projectLedgerChain,
	type RecognitionResult,
	type RegisteredOperationSemantics,
	type ResourceAddress,
	type RuleEvaluation,
	resolveEnumSchemaForComparison,
	resourceScopeCovers,
	type StepJournal,
	selectorMatchesResource,
	semanticArtifactId,
	serverVersionNum,
	TRANSITION_LESSOR_REJECTION,
	type TransactionalCompletionRecord,
	type TransitionExecutionClient,
	type TransitionLeaseFailure,
	type TransitionLessor,
	type TransitionPack,
	type TransitionQueryClient,
	type TransitionRule,
	type TransitionRunMetadata,
	type TransitionRunPersister,
	type TransitionSessionClient,
	transitionPlanDigest,
	type ValidatedManagedStepManifest,
	validateDeclarationModel,
	validateNormalizedManagedStepManifest,
	validateTransitionRelationalInvariants,
} from './transition/index.js';
export {
	admitOutcomeClaim,
	claimIdForToken,
	consumeClaimToken,
	mintClaimToken,
} from './transition/outcome-protocol.js';
export {
	markTransitionClientCompromised,
	transitionPhysicalSessionIsCompromised,
} from './transition/transition-lessor.js';
