/**
 * Scans markdown sources and emits one test file per markdown bucket
 * into __generated__/, with ONE test PER BLOCK (not per file).
 *
 * Each block is wrapped in its own `it(...)` so a single bad block cannot
 * prevent other blocks from being checked. Blocks execute via a dynamic
 * import that wraps the code in an async IIFE with the standard @dbsp API
 * surface pre-imported.
 *
 * Run: `pnpm tsx tests/docs-verification/generate-tests.ts`
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { doctestSources, looksLikeFragment } from './doc-sources.js';
import { extractBlocks } from './doctest.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');
const GENERATED = join(__dirname, '__generated__');

/** When true, blocks annotated with `// doctest: real-db-only` are included as runnable tests. */
const REAL_DB = process.env.DBSP_DOCTEST_REAL_DB === '1';

const SOURCES = doctestSources(ROOT);

mkdirSync(GENERATED, { recursive: true });

let totalBlocks = 0;
let skippedBlocks = 0;
let skippedFragment = 0;
let skippedExplicit = 0;
let skippedRealDbOnly = 0;
let runnableBlocks = 0;

for (const [bucket, mdFiles] of Object.entries(SOURCES)) {
	const cases: string[] = [];
	for (const mdFile of mdFiles) {
		const absMd = join(ROOT, mdFile);
		let blocks: ReturnType<typeof extractBlocks>;
		try {
			blocks = extractBlocks(absMd);
		} catch {
			cases.push(
				`it.skip(${JSON.stringify(`${mdFile} — file not found`)}, () => {});`,
			);
			continue;
		}
		if (blocks.length === 0) continue;

		for (const block of blocks) {
			totalBlocks++;
			const label = JSON.stringify(
				`${block.file}:${block.line} (block ${block.index})`,
			);

			if (block.annotations.skip) {
				skippedBlocks++;
				skippedExplicit++;
				cases.push(`it.skip(${label}, () => {});`);
				continue;
			}
			if (block.annotations.realDbOnly === true && !REAL_DB) {
				skippedBlocks++;
				skippedRealDbOnly++;
				cases.push(`it.skip(${label}, () => {});`);
				continue;
			}
			if (looksLikeFragment(block.code)) {
				skippedBlocks++;
				skippedFragment++;
				cases.push(`it.skip(${label} + ' — fragment', () => {});`);
				continue;
			}

			runnableBlocks++;
			// The block body is passed AS A STRING to runBlock, which wraps it
			// in an async IIFE and evaluates via dynamic import. That way parse
			// errors in one block don't abort other blocks' tests.
			const encoded = JSON.stringify(block.code);
			cases.push(
				`it(${label}, async () => { await runBlock(${encoded}, ${JSON.stringify(block.file)}, ${block.line}, { realDbOnly: ${block.annotations.realDbOnly === true} }); });`,
			);
		}
	}

	if (cases.length === 0) continue;

	const header = generatedHeader();
	const body = `describe(${JSON.stringify(bucket)}, () => {\n\t${cases.join('\n\t')}\n});\n`;

	writeFileSync(join(GENERATED, `${bucket}.test.ts`), `${header}${body}`);
}

function generatedHeader(): string {
	return `// GENERATED by tests/docs-verification/generate-tests.ts — DO NOT EDIT.
// Regenerate with: pnpm tsx tests/docs-verification/generate-tests.ts
import { describe, it, expect } from 'vitest';
import { runBlock } from '../runner.js';
// eslint-disable-next-line @typescript-eslint/no-unused-vars

`;
}

const mode = REAL_DB ? 'real-db' : 'compile-only';
const realDbSuffix =
	skippedRealDbOnly > 0
		? `, real-db-only: ${skippedRealDbOnly} [REAL_DB=0]`
		: '';
console.log(
	`Generated ${totalBlocks} block cases across ${Object.keys(SOURCES).length} buckets: ${runnableBlocks} runnable, ${skippedBlocks} skipped` +
		` (fragment: ${skippedFragment}, explicit-skip: ${skippedExplicit}${realDbSuffix}) [mode: ${mode}].`,
);
