/**
 * Scans markdown sources and emits one test file per markdown bucket
 * into __generated__/, with ONE test PER BLOCK (not per file).
 *
 * Each block is wrapped in its own `it(...)` so a single bad block cannot
 * prevent other blocks from being checked. Blocks execute via a dynamic
 * import that wraps the code in an async IIFE with the standard @dbsp API
 * surface pre-imported.
 *
 * Run: `pnpm tsx tests/docs-verification/generate-tests.ts`
 */
import { mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { extractBlocks } from './doctest.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');
const GENERATED = join(__dirname, '__generated__');

/** When true, blocks annotated with `// doctest: real-db-only` are included as runnable tests. */
const REAL_DB = process.env.DBSP_DOCTEST_REAL_DB === '1';

const SOURCES: Record<string, string[]> = {
	readme: ['README.md'],
	'package-readmes': [
		'packages/types/README.md',
		'packages/nql/README.md',
		'packages/core/README.md',
		'packages/adapter-pgsql/README.md',
		'packages/cli/README.md',
		'packages/mcp-server/README.md',
	],
	'site-index': [
		'packages/docs/index.md',
		'packages/docs/patterns.md',
		'packages/docs/comparison.md',
		'packages/docs/roadmap.md',
	],
	'site-guides': collectDir('packages/docs/guide'),
	'site-api': collectDir('packages/docs/api'),
	'site-nql': collectDir('packages/docs/nql'),
};

function collectDir(rel: string): string[] {
	const abs = join(ROOT, rel);
	try {
		return readdirSync(abs)
			.filter((f) => f.endsWith('.md'))
			.filter((f) => statSync(join(abs, f)).isFile())
			.map((f) => join(rel, f));
	} catch {
		return [];
	}
}

/**
 * Heuristic fragment detection — blocks that can't possibly execute on their
 * own because they're incomplete syntax. Docs authors can mark explicit
 * fragments with `// doctest: skip`; this catches obvious ones automatically.
 */
function looksLikeFragment(code: string): boolean {
	const trimmed = code.trim();
	if (!trimmed) return true;
	// Starts with a method chain — pipe continuation
	if (/^\.\w/.test(trimmed)) return true;
	// Starts with a binary operator — continuation
	if (/^(\||&&|\|\||\?|,)/.test(trimmed)) return true;
	// Only a destructuring/spread fragment
	if (/^(\.{3}|\{\s*\.{3})/.test(trimmed)) return true;
	return false;
}

mkdirSync(GENERATED, { recursive: true });

let totalBlocks = 0;
let skippedBlocks = 0;
let runnableBlocks = 0;

for (const [bucket, mdFiles] of Object.entries(SOURCES)) {
	const cases: string[] = [];
	for (const mdFile of mdFiles) {
		const absMd = join(ROOT, mdFile);
		let blocks: ReturnType<typeof extractBlocks>;
		try {
			blocks = extractBlocks(absMd);
		} catch {
			cases.push(
				`it.skip(${JSON.stringify(`${mdFile} — file not found`)}, () => {});`,
			);
			continue;
		}
		if (blocks.length === 0) continue;

		for (const block of blocks) {
			totalBlocks++;
			const label = JSON.stringify(
				`${block.file}:${block.line} (block ${block.index})`,
			);

			const shouldSkip =
				block.annotations.skip ||
				(block.annotations.realDbOnly === true && !REAL_DB);
			if (shouldSkip) {
				skippedBlocks++;
				cases.push(`it.skip(${label}, () => {});`);
				continue;
			}
			if (looksLikeFragment(block.code)) {
				skippedBlocks++;
				cases.push(`it.skip(${label} + ' — fragment', () => {});`);
				continue;
			}

			runnableBlocks++;
			// The block body is passed AS A STRING to runBlock, which wraps it
			// in an async IIFE and evaluates via dynamic import. That way parse
			// errors in one block don't abort other blocks' tests.
			const encoded = JSON.stringify(block.code);
			cases.push(
				`it(${label}, async () => { await runBlock(${encoded}, ${JSON.stringify(block.file)}, ${block.line}); });`,
			);
		}
	}

	if (cases.length === 0) continue;

	const header = generatedHeader();
	const body = `describe(${JSON.stringify(bucket)}, () => {\n\t${cases.join('\n\t')}\n});\n`;

	writeFileSync(join(GENERATED, `${bucket}.test.ts`), `${header}${body}`);
}

function generatedHeader(): string {
	return `// GENERATED by tests/docs-verification/generate-tests.ts — DO NOT EDIT.
// Regenerate with: pnpm tsx tests/docs-verification/generate-tests.ts
import { describe, it, expect } from 'vitest';
import { runBlock } from '../runner.js';
// eslint-disable-next-line @typescript-eslint/no-unused-vars

`;
}

const mode = REAL_DB ? 'real-db' : 'compile-only';
console.log(
	`Generated ${totalBlocks} block cases across ${Object.keys(SOURCES).length} buckets: ${runnableBlocks} runnable, ${skippedBlocks} skipped (fragment/explicit-skip) [mode: ${mode}].`,
);
