import type { QueryIntent } from './query-intent.js';

/**
 * CTE backed by unnest() arrays, optionally with WITH ORDINALITY for 0-based indexing.
 *
 * Generates:
 *   SELECT t."col1", t."col2", (t.ordinality - 1) AS "idx"
 *   FROM unnest(CAST($1 AS type[]), CAST($2 AS type[])) WITH ORDINALITY AS t("col1", "col2", ordinality)
 */
export interface UnnestCteIntent {
	readonly kind: 'unnestCte';
	readonly name: string;
	/** Column name → array of values. All arrays must have the same length. */
	readonly columns: Record<string, readonly unknown[]>;
	/** Optional column name for the 0-based ordinality index. */
	readonly indexColumn?: string;
}

/**
 * Full CTE query: one or more CTE definitions + an outer query.
 */

/**
 * CTE backed by explicit base and step QueryIntent instances (WITH RECURSIVE).
 *
 * Used by `orm.recursive(name, { base, step })` to build arbitrary
 * WITH RECURSIVE queries from query builder instances.
 *
 * Generates:
 *   WITH RECURSIVE "name" AS (
 *     <base SELECT>
 *     UNION ALL   -- or UNION when unionAll: false
 *     <step SELECT> [WHERE depth_col < maxDepth]
 *   )
 */
export interface RawCteIntent {
	readonly kind: 'rawCte';
	readonly name: string;
	readonly base: QueryIntent;
	readonly step: QueryIntent;
	/** When true, use UNION ALL (default). When false, use UNION (deduplicates). */
	readonly unionAll: boolean;
	/** Optional depth guard: inject WHERE <depthColumn> < maxDepth in the recursive step. */
	readonly maxDepth?: number;
	/** Column name tracking depth in the step query, for maxDepth injection. */
	readonly depthColumn?: string;
}

/**
 * CTE backed by a standard NQL query (non-recursive, non-unnest).
 *
 * Generated by `WITH name AS (query)` syntax in NQL.
 * Produces: `name AS (SELECT ...)`
 */
export interface SimpleCteIntent {
	readonly kind: 'simpleCte';
	readonly name: string;
	readonly query: QueryIntent;
}

export interface CteQueryIntent {
	readonly kind: 'cteQuery';
	readonly ctes: readonly (UnnestCteIntent | RawCteIntent | SimpleCteIntent)[];
	readonly query: QueryIntent;
}
